theme: beautifulhugo
baseURL: 'https://jobcespedes.dev/'
defaultContentLanguage: en
copyright: © 2023 Job Céspedes Ortiz
title: "My Dev Blog"
metaDataFormat: "yaml"
pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
footnoteReturnLinkContents: ↩
enableemoji: true
googleAnalytics: 'G-42FQ4K4QWP'
permalinks:
  posts: /:year/:month/:slug/
params:
  subtitle: "By Job Céspedes Ortiz"
  logo: img/me_avatar.png
  favicon: img/me.ico
  dateFormat: 'January 2, 2006'
  rss: true
  readingTime: true
  wordCount: true
  useHLJS: true
  # socialShare: true
  showRelatedPosts: true
  hideAuthor: true
Author:
  name: Job Céspedes Ortiz
  github: jobcespedes
  gitlab: jobcespedes
  linkedin: jobcespedes
